### Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.

- 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):<br>
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],<br>
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].<br>
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.<br>
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.<br>

In [1]:
import numpy as np

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

Ковариация:

In [4]:
cov_elementary = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)
cov_elementary

9157.839999999997

In [10]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [7]:
np.std(zp)

59.115480206118605

In [8]:
np.std(ks)

174.55340157098058

Коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков

In [11]:
cov_elementary / (np.std(zp) * np.std(ks))


0.8874900920739158

С использованием функций библиотек numpy и pandas.

In [14]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

- 2. Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:<br>
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.<br>
Известно, что в генеральной совокупности IQ распределен нормально.<br>
Найдите доверительный интервал для математического ожидания с надежностью 0.95.<br>

In [15]:
iq_temporary = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq_temporary

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [16]:
mu = iq_temporary.mean()
mu

118.1

In [17]:
variance = iq_temporary.var(ddof=1)
variance

111.21111111111111

In [18]:
s = variance**0.5
s

10.54566788359614

Доверительный интервал для математического ожидания:

In [19]:
[mu - 2.262 * s / np.sqrt(10), mu + 2.262 * s / np.sqrt(10)]

[110.55660776308164, 125.64339223691834]

- 3. Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [20]:
[174.2 - 1.96 * 5 / np.sqrt(27), 174.2 + 1.96 * 5 / np.sqrt(27)]

[172.31398912064722, 176.08601087935276]

### Тема курсовой работы
Я записался на InClass Prediction Competition (Black Friday Sales / Geekbrains Python for Data Science course competition)
Его у нас не было в ранних курсах, может будет в будущих, но не страшно.
В общем: задача состоит в том, чтобы предсказать стоимость покупок в датасете test.csv
#### Тему я взял - дисперсионный анализ c EDA -> а).EDA (рассчитать описательные статистики (мю,сигма,квартили…)+ графический анализ с выводами)
